[package]
name = "mymatch3"
version = "0.1.0"
edition = "2021"
authors = ["Emi"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.0"
rand = "0.9.0-alpha.0"